[2022-02-17 08:27:53,993] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: demo_etl.Extract_Data manual__2022-02-17T08:27:48.302798+00:00 [queued]>
[2022-02-17 08:27:54,006] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: demo_etl.Extract_Data manual__2022-02-17T08:27:48.302798+00:00 [queued]>
[2022-02-17 08:27:54,006] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-17 08:27:54,007] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-17 08:27:54,007] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-17 08:27:54,022] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): Extract_Data> on 2022-02-17 08:27:48.302798+00:00
[2022-02-17 08:27:54,029] {standard_task_runner.py:52} INFO - Started process 71445 to run task
[2022-02-17 08:27:54,038] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'demo_etl', 'Extract_Data', 'manual__2022-02-17T08:27:48.302798+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/demo_etl.py', '--cfg-path', '/tmp/tmp90airkfg', '--error-file', '/tmp/tmpe62mcazy']
[2022-02-17 08:27:54,039] {standard_task_runner.py:77} INFO - Job 21: Subtask Extract_Data
[2022-02-17 08:27:54,192] {logging_mixin.py:109} INFO - Running <TaskInstance: demo_etl.Extract_Data manual__2022-02-17T08:27:48.302798+00:00 [running]> on host f8b49ae6ae82
[2022-02-17 08:27:54,278] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=demo_etl
AIRFLOW_CTX_TASK_ID=Extract_Data
AIRFLOW_CTX_EXECUTION_DATE=2022-02-17T08:27:48.302798+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-17T08:27:48.302798+00:00
[2022-02-17 08:27:54,286] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-02-17 08:27:54,287] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
[2022-02-17 08:27:54,288] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2022-02-17 08:27:54,289] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2022-02-17 08:27:54,290] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
[2022-02-17 08:27:54,291] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-02-17 08:27:54,292] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
[2022-02-17 08:27:54,293] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2022-02-17 08:27:54,294] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
[2022-02-17 08:27:54,295] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-02-17 08:27:54,296] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
[2022-02-17 08:27:54,297] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-02-17 08:27:54,307] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/functions.py", line 11, in extract
    url_file_greentaxidata_2020 = Variable.get("url_file_greentaxidata_2020")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable url_file_greentaxidata_2020 does not exist'
[2022-02-17 08:27:54,345] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=demo_etl, task_id=Extract_Data, execution_date=20220217T082748, start_date=20220217T082753, end_date=20220217T082754
[2022-02-17 08:27:54,360] {standard_task_runner.py:92} ERROR - Failed to execute job 21 for task Extract_Data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/functions.py", line 11, in extract
    url_file_greentaxidata_2020 = Variable.get("url_file_greentaxidata_2020")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable url_file_greentaxidata_2020 does not exist'
[2022-02-17 08:27:54,455] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-17 08:27:54,504] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
