[2022-02-18 07:43:10,815] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: my_dag.task_a scheduled__2022-02-17T00:00:00+00:00 [queued]>
[2022-02-18 07:43:10,878] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: my_dag.task_a scheduled__2022-02-17T00:00:00+00:00 [queued]>
[2022-02-18 07:43:10,879] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-18 07:43:10,879] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-18 07:43:10,879] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-18 07:43:11,210] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): task_a> on 2022-02-17 00:00:00+00:00
[2022-02-18 07:43:11,213] {standard_task_runner.py:52} INFO - Started process 264 to run task
[2022-02-18 07:43:11,227] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'task_a', 'scheduled__2022-02-17T00:00:00+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpxtxo3q3e', '--error-file', '/tmp/tmprrg52b4c']
[2022-02-18 07:43:11,229] {standard_task_runner.py:77} INFO - Job 171: Subtask task_a
[2022-02-18 07:43:11,389] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.task_a scheduled__2022-02-17T00:00:00+00:00 [running]> on host 025baa70c69a
[2022-02-18 07:43:11,931] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=task_a
AIRFLOW_CTX_EXECUTION_DATE=2022-02-17T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-17T00:00:00+00:00
[2022-02-18 07:43:11,933] {logging_mixin.py:109} INFO - /opt/***
[2022-02-18 07:43:11,933] {python.py:175} INFO - Done. Returned value was: None
[2022-02-18 07:43:11,946] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=task_a, execution_date=20220217T000000, start_date=20220218T074310, end_date=20220218T074311
[2022-02-18 07:43:12,020] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-18 07:43:12,050] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
